apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend-something
  name: frontend-something
  namespace: bekhzod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-something
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-something
    spec:
      nodeSelector:
        kubernetes.io/hostname: node2
      containers:
        - image: nvrbckdown/frontend-something
          name: frontend-something
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
