apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 9ce45d6fcb2bab0b51a0cb67e5c1df0e9afbd090c7b7b59cff57ab14a511b4f6
    cni.projectcalico.org/podIP: 10.233.68.129/32
    cni.projectcalico.org/podIPs: 10.233.68.129/32
  creationTimestamp: "2024-02-12T14:23:41Z"
  labels:
    run: nginx2
    last: final
    author: Bekhzod
  name: nginx2
  namespace: bekhzod
  resourceVersion: "4962947"
  uid: 40ee4a0e-3c20-45ac-b9aa-0c020279ac10
spec:
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx2
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-4549r
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node4
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-4549r
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-02-12T14:23:41Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-02-12T14:23:43Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-02-12T14:23:43Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-02-12T14:23:41Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: containerd://ab8bbcbd7d90a5d433b2b52f35128837aa02aba73715d225ea21406df186c895
      image: docker.io/library/nginx:latest
      imageID: docker.io/library/nginx@sha256:5f44022eab9198d75939d9eaa5341bc077eca16fa51d4ef32d33f1bd4c8cbe7d
      lastState: {}
      name: nginx2
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-02-12T14:23:43Z"
  hostIP: 95.216.206.151
  phase: Running
  podIP: 10.233.68.129
  podIPs:
    - ip: 10.233.68.129
  qosClass: BestEffort
  startTime: "2024-02-12T14:23:41Z"
