apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2024-02-12T16:48:08Z"
  generation: 1
  name: node-printer
  namespace: bekhzod
  resourceVersion: "5059728"
  uid: 732ab26c-ecb9-4e85-b513-000bd1708d7b
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: node-printer
    spec:
      parallelism: 5
      completions: 10
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: nginx
              imagePullPolicy: Always
              name: node-printer
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
